spring:
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:postgresql://db:5432/inventory-tracker
    username: inventory-tracker
    password: inventory-tracker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  session:
    timeout: 1800
server:
  port: 8081
inventorytracker:
  baseUrl: http://localhost
