spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-tracker
    username: inventory-tracker
    password: inventory-tracker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8084